# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [148]:
# import numpy and pandas
import numpy as np
import pandas as pd

# Challenge 1 - Independent Sample T-tests

In this challenge, we will be using the Pokemon dataset. Before applying statistical methods to this data, let's first examine the data.

To load the data, run the code below.

In [4]:
# Run this code:
pokemon = pd.read_csv('../pokemon.csv')

Let's start off by looking at the `head` function in the cell below.

In [6]:
# Your code here:

pokemon.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

The first thing we would like to do is compare the legendary Pokemon to the regular Pokemon. To do this, we should examine the data further. What is the count of legendary vs. non legendary Pokemons?

In [44]:
# Your code here:

legendarios = pokemon[pokemon["Legendary"] == True]
legendarios.shape


(65, 13)

In [17]:
no_legendarios = pokemon[pokemon["Legendary"] == False]
no_legendarios.shape

(735, 13)

Compute the mean and standard deviation of the total points for both legendary and non-legendary Pokemon.

In [76]:
# Your code here:
media_legen=legendarios["Total"].mean()
std_legen=legendarios["Total"].std()

media_nolegen=no_legendarios["Total"].mean()
std_nolegen=no_legendarios["Total"].std()
print(media_legen, std_legen)

637.3846153846154 60.93738905315344


The computation of the mean might give us a clue regarding how the statistical test may turn out; However, it certainly does not prove whether there is a significant difference between the two groups.

In the cell below, use the `ttest_ind` function in `scipy.stats` to compare the the total points for legendary and non-legendary Pokemon. Since we do not have any information about the population, assume the variances are not equal.

In [141]:
# Your code here:
from scipy.stats import ttest_rel, ttest_ind, ttest_1samp


ttest_ind(legendarios["Total"], no_legendarios["Total"],equal_var=False)



Ttest_indResult(statistic=25.8335743895517, pvalue=9.357954335957446e-47)

In [85]:
from statsmodels.stats import weightstats as w 
w.ztest(legendarios["Total"], no_legendarios["Total"], 0)

(16.386116965872425, 2.4031368278343178e-60)

What do you conclude from this test? Write your conclusions below.

In [6]:
# Your conclusions here:
#dado que pvalue se aproxima a 0 se puede asumir que las medias son diferentes




How about we try to compare the different types of pokemon? In the cell below, list the types of Pokemon from column `Type 1` and the count of each type.

In [88]:
# Your code here:
pokemon["Type 1"].value_counts()

Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Dragon       32
Ground       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        17
Flying        4
Name: Type 1, dtype: int64


Since water is the largest group of Pokemon, compare the mean and standard deviation of water Pokemon to all other Pokemon.

In [73]:
# Your code here:
agua=pokemon[pokemon["Type 1"] == "Water"]
no_agua=pokemon[pokemon["Type 1"] != "Water"]

print(agua["Total"].mean(), agua["Total"].std())
print(no_agua["Total"].mean(), no_agua["Total"].std())

430.45535714285717 113.1882660643146
435.85901162790697 121.0916823020807


Ttest_relResult(statistic=-0.9547634690546188, pvalue=0.34177199312338336)

Perform a hypothesis test comparing the mean of total points for water Pokemon to all non-water Pokemon. Assume the variances are equal. 


In [121]:
# Your code here:
# hipotesis: No hay diferencia significativa


no_agua112 = no_agua.sample(n=112)

ttest_rel(agua["Total"],no_agua112["Total"])




Ttest_relResult(statistic=-0.714050224039988, pvalue=0.47669495112297355)

Write your conclusion below.

In [122]:
# Your conclusions here:
#dado que PValue no tiende a 0 se puede asumir que no hay diferencia significativas



otra manera
creo que esta esta bien 

In [129]:
#h0: No hay diferencia significativa
z_score, p_value = w.ztest(agua["Total"],
                           no_agua["Total"],
                           value=0, 
                           alternative='two-sided',
                           usevar='pooled',
                           ddof=1)
z_score, p_value

(-0.4418547448849676, 0.6585943204400648)

# Challenge 2 - Matched Pairs Test

In this challenge we will compare dependent samples of data describing our Pokemon. Our goal is to see whether there is a significant difference between each Pokemon's defense and attack scores. Our hypothesis is that the defense and attack scores are equal. In the cell below, import the `ttest_rel` function from `scipy.stats` and compare the two columns to see if there is a statistically significant difference between them.

In [134]:
# Your code here:
pokemon["Attack"]

ttest_rel(pokemon["Attack"],pokemon["Defense"])


Ttest_relResult(statistic=4.325566393330478, pvalue=1.7140303479358558e-05)

Describe the results of the test in the cell below.

In [12]:
# Your conclusions here:
#son significativamente diferentes porque  pvalue tiende a 0 



We are also curious about whether therer is a significant difference between the mean of special defense and the mean of special attack. Perform the hypothesis test in the cell below. 

In [136]:
# Your code here:
ttest_rel(pokemon["Sp. Atk"],pokemon["Sp. Def"])




Ttest_relResult(statistic=0.853986188453353, pvalue=0.3933685997548122)

Describe the results of the test in the cell below.

In [14]:
# Your conclusions here:
#no son signidficativamente diferentes porque el pvalue no se aproxima a 0



As you may recall, a two sample matched pairs test can also be expressed as a one sample test of the difference between the two dependent columns.

Import the `ttest_1samp` function and perform a one sample t-test of the difference between defense and attack. Test the hypothesis that the difference between the means is zero. Confirm that the results of the test are the same.

In [145]:
# Your code here:
diff=(pokemon["Attack"]-pokemon["Defense"])

ttest_1samp(diff, 0)


Ttest_1sampResult(statistic=4.325566393330478, pvalue=1.7140303479358558e-05)

In [146]:
#da lo mismo

# Bonus Challenge - The Chi-Square Test

The Chi-Square test is used to determine whether there is a statistically significant difference in frequencies. In other words, we are testing whether there is a relationship between categorical variables or rather when the variables are independent. This test is an alternative to Fisher's exact test and is used in scenarios where sample sizes are larger. However, with a large enough sample size, both tests produce similar results. Read more about the Chi Squared test [here](https://en.wikipedia.org/wiki/Chi-squared_test).

In the cell below, create a contingency table using `pd.crosstab` comparing whether a Pokemon is legenadary or not and whether the Type 1 of a Pokemon is water or not.

In [175]:
# Your code here:

cross=pd.crosstab(pokemon.Legendary, pokemon['Type 1'] == "Water", )
cross

Type 1     False  True
Legendary             
False        627   108
True          61     4

Perform a chi-squared test using the `chi2_contingency` function in `scipy.stats`. You can read the documentation of the function [here](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.chi2_contingency.html).

In [156]:
from scipy.stats import  chi2, chi2_contingency

# Your code here:
chi2_contingency(cross)



(2.9429200762850503,
 0.08625467249550949,
 1,
 array([[632.1, 102.9],
        [ 55.9,   9.1]]))

Based on a 95% confidence, should we reject the null hypothesis?

In [19]:
# Your answer here:
#no se puede aseverar con una seguridad de 95% asociacion entre ser legendario o no y entre ser de agua o no

In [171]:

cross[1][1] =3

In [172]:
cross

Type 1     False  True
Legendary             
False        627   108
True          61     3

In [173]:
chi2_contingency(cross)


(4.126849408442501,
 0.042207862428081645,
 1,
 array([[632.89111389, 102.10888611],
        [ 55.10888611,   8.89111389]]))

In [180]:
pokemon["iswater"]=(pokemon['Type 1'] == "Water")|(pokemon['Type 2'] == "Water")

In [185]:
cross=pd.crosstab(pokemon.Legendary, pokemon['iswater'] )
cross

iswater    False  True
Legendary             
False        614   121
True          60     5

In [186]:
chi2_contingency(cross)


(2.832287068949092,
 0.09238670568372255,
 1,
 array([[619.2375, 115.7625],
        [ 54.7625,  10.2375]]))

In [ ]:
#asi tampoco :(